### ISSUE TITLE
CVBS support?

### ISSUE THREAD

**Issue by ganadevprajapathy** [moefh/pico-vga-6bit-demo#1]
Can you guide how to implement it for cvbs

**Comment by moefh** [comment]
Sorry, I don't know how to generate full color composite video output with the Pico, it would have to be a very different project from this one. Composite video is trickier than VGA, since all information must be encoded in a single signal (as opposed to VGA, where each color component is separated).

Other people managed monochromatic composite video output (see [this project](https://github.com/breakintoprogram/pico-mposite) for example), but I haven't seen anyone doing color output.
